// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

type ContactDocumentDataSlicesSlice = never;

/**
 * Content for Contact documents
 */
interface ContactDocumentData {
  /**
   * Slice Zone field in *Contact*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<ContactDocumentDataSlicesSlice>; /**
   * Meta Title field in *Contact*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: contact.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Contact*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: contact.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Contact*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Contact document from Prismic
 *
 * - **API ID**: `contact`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ContactDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<ContactDocumentData>,
    "contact",
    Lang
  >;

type HomeDocumentDataSlicesSlice = never;

/**
 * Content for Page d'accueil documents
 */
interface HomeDocumentData {
  /**
   * Slice Zone field in *Page d'accueil*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<HomeDocumentDataSlicesSlice>; /**
   * Meta Title field in *Page d'accueil*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: home.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Page d'accueil*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: home.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Page d'accueil*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Page d'accueil document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<HomeDocumentData>, "home", Lang>;

type MentionsDocumentDataSlicesSlice = never;

/**
 * Content for Mentions Légales documents
 */
interface MentionsDocumentData {
  /**
   * Slice Zone field in *Mentions Légales*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: mentions.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<MentionsDocumentDataSlicesSlice>; /**
   * Meta Title field in *Mentions Légales*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: mentions.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Mentions Légales*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: mentions.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Mentions Légales*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: mentions.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Mentions Légales document from Prismic
 *
 * - **API ID**: `mentions`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type MentionsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<MentionsDocumentData>,
    "mentions",
    Lang
  >;

/**
 * Content for Menu documents
 */
interface MenuDocumentData {
  /**
   * Liens field in *Menu*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: menu.links
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  links: prismic.Repeatable<
    prismic.LinkField<string, string, unknown, prismic.FieldState, never>
  >;
}

/**
 * Menu document from Prismic
 *
 * - **API ID**: `menu`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type MenuDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<MenuDocumentData>, "menu", Lang>;

type WebsiteDocumentDataSlicesSlice =
  | IntroTextSlice
  | TwoColumnContentSplitSlice
  | VideoFeatureCardSlice;

/**
 * Content for Site web documents
 */
interface WebsiteDocumentData {
  /**
   * Titre field in *Site web*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: website.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Image principale field in *Site web*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: website.img
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  img: prismic.ImageField<never>;

  /**
   * Lien du site field in *Site web*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: website.weblink
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  weblink: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Slice Zone field in *Site web*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: website.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<WebsiteDocumentDataSlicesSlice>; /**
   * Meta Title field in *Site web*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: website.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Site web*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: website.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Site web*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: website.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Site web document from Prismic
 *
 * - **API ID**: `website`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type WebsiteDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<WebsiteDocumentData>,
    "website",
    Lang
  >;

type WebsitesDocumentDataSlicesSlice = never;

/**
 * Content for Sites web documents
 */
interface WebsitesDocumentData {
  /**
   * Slice Zone field in *Sites web*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: websites.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<WebsitesDocumentDataSlicesSlice>; /**
   * Meta Title field in *Sites web*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: websites.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Sites web*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: websites.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Sites web*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: websites.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Sites web document from Prismic
 *
 * - **API ID**: `websites`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type WebsitesDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<WebsitesDocumentData>,
    "websites",
    Lang
  >;

export type AllDocumentTypes =
  | ContactDocument
  | HomeDocument
  | MentionsDocument
  | MenuDocument
  | WebsiteDocument
  | WebsitesDocument;

/**
 * Primary content in *Texte → Title and Description → Primary*
 */
export interface IntroTextSliceTitleAndDescriptionPrimary {
  /**
   * Title field in *Texte → Title and Description → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: intro_text.title_and_description.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Description field in *Texte → Title and Description → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: intro_text.title_and_description.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;
}

/**
 * Title and Description variation for Texte Slice
 *
 * - **API ID**: `title_and_description`
 * - **Description**: Displays a heading followed by a description or explanatory paragraph.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type IntroTextSliceTitleAndDescription = prismic.SharedSliceVariation<
  "title_and_description",
  Simplify<IntroTextSliceTitleAndDescriptionPrimary>,
  never
>;

/**
 * Slice variation for *Texte*
 */
type IntroTextSliceVariation = IntroTextSliceTitleAndDescription;

/**
 * Texte Shared Slice
 *
 * - **API ID**: `intro_text`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type IntroTextSlice = prismic.SharedSlice<
  "intro_text",
  IntroTextSliceVariation
>;

/**
 * Item in *Images → Default → Primary → Images*
 */
export interface TwoColumnContentSplitSliceDefaultPrimaryImagesItem {
  /**
   * Image field in *Images → Default → Primary → Images*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: two_column_content_split.default.primary.images[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;
}

/**
 * Primary content in *Images → Default → Primary*
 */
export interface TwoColumnContentSplitSliceDefaultPrimary {
  /**
   * Images field in *Images → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: two_column_content_split.default.primary.images[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  images: prismic.GroupField<
    Simplify<TwoColumnContentSplitSliceDefaultPrimaryImagesItem>
  >;
}

/**
 * Default variation for Images Slice
 *
 * - **API ID**: `default`
 * - **Description**: Standard two-column layout. Supports variations in background color and different content types for each column (text, list, images, info blocks).
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TwoColumnContentSplitSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TwoColumnContentSplitSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Images*
 */
type TwoColumnContentSplitSliceVariation = TwoColumnContentSplitSliceDefault;

/**
 * Images Shared Slice
 *
 * - **API ID**: `two_column_content_split`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TwoColumnContentSplitSlice = prismic.SharedSlice<
  "two_column_content_split",
  TwoColumnContentSplitSliceVariation
>;

/**
 * Primary content in *Video → Default → Primary*
 */
export interface VideoFeatureCardSliceDefaultPrimary {
  /**
   * Video field in *Video → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: video_feature_card.default.primary.videoID
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  videoID: prismic.KeyTextField;
}

/**
 * Default variation for Video Slice
 *
 * - **API ID**: `default`
 * - **Description**: Displays embedded video (Vimeo, YouTube, etc.), a large title with optional branding/logo, description, author, and call-to-action. Optional social/interaction icons.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type VideoFeatureCardSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<VideoFeatureCardSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Video*
 */
type VideoFeatureCardSliceVariation = VideoFeatureCardSliceDefault;

/**
 * Video Shared Slice
 *
 * - **API ID**: `video_feature_card`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type VideoFeatureCardSlice = prismic.SharedSlice<
  "video_feature_card",
  VideoFeatureCardSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      ContactDocument,
      ContactDocumentData,
      ContactDocumentDataSlicesSlice,
      HomeDocument,
      HomeDocumentData,
      HomeDocumentDataSlicesSlice,
      MentionsDocument,
      MentionsDocumentData,
      MentionsDocumentDataSlicesSlice,
      MenuDocument,
      MenuDocumentData,
      WebsiteDocument,
      WebsiteDocumentData,
      WebsiteDocumentDataSlicesSlice,
      WebsitesDocument,
      WebsitesDocumentData,
      WebsitesDocumentDataSlicesSlice,
      AllDocumentTypes,
      IntroTextSlice,
      IntroTextSliceTitleAndDescriptionPrimary,
      IntroTextSliceVariation,
      IntroTextSliceTitleAndDescription,
      TwoColumnContentSplitSlice,
      TwoColumnContentSplitSliceDefaultPrimaryImagesItem,
      TwoColumnContentSplitSliceDefaultPrimary,
      TwoColumnContentSplitSliceVariation,
      TwoColumnContentSplitSliceDefault,
      VideoFeatureCardSlice,
      VideoFeatureCardSliceDefaultPrimary,
      VideoFeatureCardSliceVariation,
      VideoFeatureCardSliceDefault,
    };
  }
}
