// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  intro_text: dynamic(() => import("./Texte")),
  two_column_content_split: dynamic(() => import("./Images")),
  video_feature_card: dynamic(() => import("./Video")),
};
